name: docker-run

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Pull
        run: docker pull leniziomo/scraper:latest

      - name: Clean previous container if exists
        run: docker rm -f scrapercontainer || true

      - name: Docker Run
        run: |
          docker run \
            --name scrapercontainer \
            -e TEMPORADA='2025/2026' \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DB_PASS=${{ secrets.DB_PASS }} \
            leniziomo/scraper:latest

      - name: Export Logs
        run: docker logs scrapercontainer > logs.log 2>&1

      - name: Upload Logs Artifact
        uses: actions/upload-artifact@v5
        with:
          name: scraper-log
          path: logs.log

      - name: Cleanup container
        run: docker rm scrapercontainer || true
